# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window2(object):
    def __init__(self):
        super().__init__()
        self.student_counter = 1
    def setupUi(self, Window2):
        Window2.setObjectName("Window2")
        Window2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Window2)
        self.centralwidget.setObjectName("centralwidget")
        self.Titre_Liste = QtWidgets.QLabel(self.centralwidget)
        self.Titre_Liste.setGeometry(QtCore.QRect(50, 10, 41, 16))
        self.Titre_Liste.setObjectName("Titre_Liste")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(353, 0, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Titre_Contraintes = QtWidgets.QLabel(self.centralwidget)
        self.Titre_Contraintes.setGeometry(QtCore.QRect(400, 10, 81, 16))
        self.Titre_Contraintes.setObjectName("Titre_Contraintes")
        self.Text_Prenom1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_Prenom1.setGeometry(QtCore.QRect(40, 70, 111, 31))
        self.Text_Prenom1.setObjectName("Text_Prenom1")
        self.Text_Prenom1.setPlaceholderText('Prénom')
        self.Titre_Prenom = QtWidgets.QLabel(self.centralwidget)
        self.Titre_Prenom.setGeometry(QtCore.QRect(60, 50, 47, 13))
        self.Titre_Prenom.setObjectName("Titre_Prenom")
        self.Titre_Nom = QtWidgets.QLabel(self.centralwidget)
        self.Titre_Nom.setGeometry(QtCore.QRect(200, 50, 47, 13))
        self.Titre_Nom.setObjectName("Titre_Nom")
        self.Text_Nom1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_Nom1.setGeometry(QtCore.QRect(170, 70, 111, 31))
        self.Text_Nom1.setObjectName("Text_Nom1")
        self.Text_Nom1.setPlaceholderText('Nom')
        self.Titre_Eleve = QtWidgets.QLabel(self.centralwidget)
        self.Titre_Eleve.setGeometry(QtCore.QRect(420, 50, 47, 13))
        self.Titre_Eleve.setObjectName("Titre_Eleve")
        self.Menu_Eleve = QtWidgets.QSpinBox(self.centralwidget)
        self.Menu_Eleve.setGeometry(QtCore.QRect(420, 70, 111, 22))
        self.Menu_Eleve.setObjectName("Menu_Eleve")
        self.Menu_Contrainte = QtWidgets.QSpinBox(self.centralwidget)
        self.Menu_Contrainte.setGeometry(QtCore.QRect(550, 70, 121, 22))
        self.Menu_Contrainte.setObjectName("Menu_Contrainte")
        self.Titre_Contrainte = QtWidgets.QLabel(self.centralwidget)
        self.Titre_Contrainte.setGeometry(QtCore.QRect(550, 50, 81, 16))
        self.Titre_Contrainte.setObjectName("Titre_Contrainte")
        self.Num_1 = QtWidgets.QLabel(self.centralwidget)
        self.Num_1.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.Num_1.setObjectName("Num_1")
        self.Bouton_AjouterEleve = QtWidgets.QPushButton(self.centralwidget)
        self.Bouton_AjouterEleve.setGeometry(QtCore.QRect(10, 50, 31, 21))
        self.Bouton_AjouterEleve.setObjectName("Bouton_AjouterEleve")
        self.Bouton_AjouterEleve.clicked.connect(self.add_student_row)
        self.Bouton_AjouterContrainte = QtWidgets.QPushButton(self.centralwidget)
        self.Bouton_AjouterContrainte.setGeometry(QtCore.QRect(370, 70, 31, 21))
        self.Bouton_AjouterContrainte.setObjectName("Bouton_AjouterContrainte")
        Window2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Window2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window2)
        self.statusbar.setObjectName("statusbar")
        Window2.setStatusBar(self.statusbar)

        self.retranslateUi(Window2)
        QtCore.QMetaObject.connectSlotsByName(Window2)

    def retranslateUi(self, Window2):
        _translate = QtCore.QCoreApplication.translate
        Window2.setWindowTitle(_translate("Window2", "Liste et contraintes"))
        self.Titre_Liste.setText(_translate("Window2", "Liste"))
        self.Titre_Contraintes.setText(_translate("Window2", "Contraintes"))
        self.Titre_Prenom.setText(_translate("Window2", "Prénom"))
        self.Titre_Nom.setText(_translate("Window2", "Nom"))
        self.Titre_Eleve.setText(_translate("Window2", "Elève"))
        self.Titre_Contrainte.setText(_translate("Window2", "Contrainte"))
        self.Num_1.setText(_translate("Window2", "1"))
        self.Bouton_AjouterEleve.setText(_translate("Window2", "+"))
        self.Bouton_AjouterContrainte.setText(_translate("Window2", "+"))

    def add_student_row(self):
        #Augmente le compteur
        self.student_counter += 1

        #Calcule la position de la nouvelle ligne, décalage vertical de la ligne
        y_offset = 70 + (self.student_counter - 1) * 50

        #Création des widgets

        #Numéro de l'élève
        Num = QtWidgets.QLabel(self.centralwidget)
        Num.setGeometry(QtCore.QRect(20, y_offset, 16, 16))
        Num.setObjectName(f"Num_[{self.student_counter}")
        Num.setText(str(self.student_counter))
        Num.show()

        #Input prénom

        #Input Nom